name: product-sentiment
services:
    chromadb:
        image: chromadb/chroma:latest
        ports:
            - "8000:8000"
        volumes:
            - chroma_data:/chroma/.chroma
        environment:
            - IS_PERSISTENT=TRUE

volumes:
    chroma_data:
